language: ruby
cache: bundler
services:
  - postgresql
before_script:
  - cp config/database.yml.travis config/database.yml
script:
  - export RAILS_ENV=test
  - bundle exec rails db:setup
  - bundle exec rspec
  - bundle exec rubocop --config .rubocop.yml
